Revert "[New] support enumerable Symbol properties"
ljharb/js-traverse pull request #6
Opened 2024-03-11 14:29 UTC by MartyJRE

This reverts commit 7d659e78d43e69e6afc604e12b3ba3a5def0e46f.

The reason for this is that the new feature is a breaking change and should be versioned as such.

See the filed issue https://github.com/ljharb/js-traverse/issues/5.

2024-03-11 17:59 UTC, ljharb requested changes
A naive revert isn't the best solution here; it'd be to put the symbol part behind an option (ie, `(includeSymbols ? ownEnumerableKeys : objectKeys)` everywhere `ownEnumerableKeys` is currently called)

2024-03-11 22:07 UTC, MartyJRE commented
@ljharb I added options to traverse. It now only deals with string keys by default. When given `includeSymbols`: true inside the options, it functions the way you desgined.

Also added `immutable` to options to avoid having too many parameters.

2024-03-12 04:11 UTC, ljharb requested changes

2024-03-12 04:11 UTC, ljharb commented on index.js
> + * @returns {function (object: object): (string | symbol)[]}
```suggestion
 * @returns {typeof ownEnumerableKeys | typeof objectKeys}
```

2024-03-12 04:11 UTC, ljharb commented on index.js
> +			var iteratorFunction = determineIterator(options);
this can be moved up to line 109.5

2024-03-12 04:11 UTC, ljharb commented on index.js
> +	}
we can't depend on `filter` existing, and ideally not `slice` either.

2024-03-12 04:11 UTC, ljharb commented on index.js
> +	return walk(this.value, cb, Object.assign(this.options, { immutable: true }));
we definitely can't assume the existence of Object.assign.

2024-03-12 04:13 UTC, ljharb commented
(you'll also need to rebase; i pulled out the immutable → options refactor)

2024-03-12 14:31 UTC, ljharb commented on .eslintrc
> +        "max-lines": "warn"
```suggestion
        "max-lines": "warn",
```

2024-03-12 14:31 UTC, ljharb commented on index.js
> +function stripSymbols(arr, options) {
I’m confused, why would we need to strip them when we could avoid adding them in the first place?

2024-03-12 14:31 UTC, ljharb commented
Don’t worry about the automatic rebase workflow.

2024-03-16 22:03 UTC, ljharb commented
I've rebased this and condensed it down to one commit.

It's still failing 3 tests for me, and I'm not sure why.

2024-04-08 16:05 UTC, ljharb commented
@MartyJRE are you able to complete this PR? i'd like to get the fix released.

2024-04-08 19:45 UTC, ljharb approved these changes

2024-04-08 20:44 UTC, merged